name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t pagina .

      - name: Configurar llave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Preparar servidor
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          mkdir -p /home/ubuntu/app
          EOF

      - name: Copiar archivos
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" \
          --exclude=".git" \
          --exclude=".github" \
          ./ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

      - name: Desplegar aplicación
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          cd /home/ubuntu/app

          sudo docker stop pagina || true
          sudo docker rm pagina || true

          sudo docker build -t pagina .

          sudo docker run -d \
            --name pagina \
            --restart unless-stopped \
            -p 80:80 \
            pagina

          EOF